jQuery(function(){jQuery(document).ready(function(){jQuery("#prosper-conf").data("serialize",jQuery("#prosper-conf").serialize());jQuery("#hidden_PositiveMerchant").val()&&jQuery.ajax({url:"http://api.prosperent.com/api/merchant",dataType:"jsonp",data:{filterMerchantId:jQuery("#hidden_PositiveMerchant").val(),sortBy:"merchant",limit:500},success:function(b){b.data&&jQuery.each(b.data,function(b,a){jQuery("#PositiveMerchantFilters").append('<li data-savedvalue="'+a.merchantId+'" class="PositiveMerchant" data-filtype="PositiveMerchant" style="float:left;margin:0;padding:6px;" onClick="removeFilter(this);"><span><a style="text-decoration:none;" id="'+
a.merchantId+'" href="javascript:void(0);">'+a.merchant+' <i class="fa fa-times"></i></a></span></li>')})}});jQuery("#hidden_NegativeMerchant").val()&&jQuery.ajax({url:"http://api.prosperent.com/api/merchant",dataType:"jsonp",data:{filterMerchantId:jQuery("#hidden_NegativeMerchant").val(),sortBy:"merchant",limit:500},success:function(b){b.data&&jQuery.each(b.data,function(b,a){jQuery("#NegativeMerchantFilters").append('<li data-savedvalue="'+a.merchantId+'" class="NegativeMerchant" data-filtype="NegativeMerchant" style="float:left;margin:0;padding:6px;" onClick="removeFilter(this);"><span><a style="text-decoration:none;" id="'+
a.merchantId+'" href="javascript:void(0);">'+a.merchant+' <i class="fa fa-times"></i></a></span></li>')})}})});jQuery("#hidden_Positive_Merchant").val()&&newFilters("Positive_Merchant");jQuery("#hidden_Negative_Merchant").val()&&newFilters("Negative_Merchant");jQuery("#categories.ProsperCategories").autocomplete({minLength:3,source:function(a,c){jQuery.ajax({url:"http://api.prosperent.com/api/search",dataType:"jsonp",data:{api_key:"fc91d36b383ca0231ee59c5048eabedc",filterCategory:"*"+a.term+"*",enableFacets:"category",
limit:1,imageSize:"125x125"},success:function(a){var b=[];a.facets&&jQuery.each(a.facets.category,function(a,c){b.push(c.value)});b=b.sort();c(b)}})},select:function(a,c){jQuery("#categories.ProsperCategories").val(c.item.value);return!1}});jQuery(window).bind("beforeunload",function(a){if(jQuery("#prosper-conf").serialize()!=jQuery("#prosper-conf").data("serialize"))return"You have unsaved settings."});jQuery("form#prosper-conf").submit(function(){jQuery(window).unbind("beforeunload")});if(jQuery("#hidden_ProsperCategories").val()){var a=
jQuery("#hidden_ProsperCategories").val();jQuery.ajax({url:"http://api.prosperent.com/api/search",dataType:"jsonp",data:{api_key:"fc91d36b383ca0231ee59c5048eabedc",filterCategory:a.replace(/_/g," "),limit:1,imageSize:"75x75"},success:function(a){jQuery("#prosperTotalResults").append("Total Results In Shop With These Category Filters: <span>"+a.totalRecordsFound.toLocaleString()+"</span>")}})}});
function addNewCategory(){var a=jQuery("#categories.ProsperCategories").val(),b=jQuery("#hidden_ProsperCategories").val();jQuery("#hidden_ProsperCategories").val(function(c,d){return b+a.replace(/ /g,"_")+"|"});jQuery.ajax({url:"http://api.prosperent.com/api/search",dataType:"jsonp",data:{api_key:"fc91d36b383ca0231ee59c5048eabedc",filterCategory:a+"*",limit:1,imageSize:"75x75"},success:function(b){jQuery("#ProsperCategoryFilters").append('<li data-savedvalue="'+a.replace(/ /g,"_")+'" class="ProsperCategories" data-filType="ProsperCategories" style="float:left;margin:0;padding:6px;" onClick="removeFilter(this);"><span><a style="text-decoration:none;" id="'+
a.replace(/ /g,"_")+'" href="javascript:void(0);">'+a+" ("+b.totalRecordsFound.toLocaleString()+') <i class="fa fa-times"></i></a></span></li>')}});jQuery("#categories.ProsperCategories").val("")}
function newFilters(a){jQuery.ajax({url:"http://api.prosperent.com/api/merchant",data:{filterMerchant:jQuery("#hidden_"+a).val(),limit:500},contentType:"application/json; charset=utf-8",dataType:"jsonp",success:function(b){jQuery.each(b.data,function(b,d){jQuery("#hidden_"+a.replace(/_/g,"")).val(function(a,b){return b+d.merchantId+"|"});jQuery("#hidden_"+a).val("")})},error:function(){}})}
function addingNewMerchantFilter(a){jQuery("#"+a.id).autocomplete({minLength:3,source:function(a,c){jQuery.ajax({url:"http://api.prosperent.com/api/merchant",dataType:"jsonp",data:{filterMerchant:jQuery.isNumeric(a.term)&&5<a.term.length?"":a.term+"*",filterMerchantId:jQuery.isNumeric(a.term)&&5<a.term.length?a.term:"",sortBy:"merchant",limit:10},success:function(a){var b=[];a.data&&jQuery.each(a.data,function(a,c){b.push({label:c.merchant,value:c.merchantId})});c(b)}})},select:function(b,c){jQuery("#hidden_"+
a.id).val().match(c.item.value)||jQuery("#hidden_"+a.id).val(function(a,b){return b+c.item.value+"|"});jQuery("#"+a.id).val("");jQuery("#"+a.id+"Filters").append('<li data-savedvalue="'+c.item.value+'" class="'+a.id+'" data-filtype="'+a.id+'" style="float:left;margin:0;padding:6px;" onClick="removeFilter(this);"><span><a style="text-decoration:none;" id="'+c.item.value+'" href="javascript:void(0);">'+c.item.label+' <i class="fa fa-times"></i></a></span></li>');return!1}})}
function removeFilter(a){var b=new RegExp(jQuery(a).attr("data-savedvalue")+"\\|","g"),c=a.className,b=jQuery("#hidden_"+c).val().replace(b,"");jQuery("#hidden_"+c).val(b);jQuery("."+c+"[data-savedvalue='"+jQuery(a).attr("data-savedvalue")+"']").empty()};